### ISSUE TITLE
merge branch main into master and delete main

### ISSUE THREAD

**Issue by Chaotique** [Macburger13/AiV#1]
Dear McBurger,

when I wrote yesterday that your task was incomplete, I didn't see that you have two branches, one main and one master, and that on main you actually have fulfilled the task. 
Still, as I'll explain today in the lecture, it would make sense to delete main, as master is actually your central branch.
Therefore at first, make master your default branch on github.com: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

If you have main also locally, type this locally:

git checkout master
git merge main
git branch -d main
git push origin --delete main

Otherwise (if you don't have a local branch main), just delete the main branch on github.com: go to the list of branches, click "View all branches", and delete main.

Task done. I still have to find out your real name (for grading).
All the best,
Chaotique

**Comment by Macburger13** [comment]
Hi,

Okay I'll check it out. Before deleting the main branche I'm going to copy the docs to master. 

My name is Victor Rodriguez,
Thank you!
